-- Availability exceptions: let a host unpaint part of a recurring window.
--
-- Until now `set_availability_range(p_open => false)` could only carve up rows
-- in `availability_slots`. Time generated by a meeting type's
-- `weekly_availability` was impossible to remove: closing 12:00-13:00 on a
-- Monday covered by a 09:00-17:00 rule wrote nothing and removed no slots.
--
-- A row is now either an opening (`kind = 'open'`) or an exception
-- (`kind = 'blocked'`). Effective availability is
--   (weekly rules UNION openings) MINUS exceptions
-- so an exception can punch a hole in a recurring window, and re-painting the
-- same range removes the exception and restores the rule.

alter table public.availability_slots
  add column kind text not null default 'open'
    check (kind in ('open', 'blocked'));

drop index if exists availability_slots_user_time_idx;
drop index if exists availability_slots_event_type_idx;

create index availability_slots_user_time_idx
  on public.availability_slots(user_id, kind, start_time, end_time);
create index availability_slots_event_type_idx
  on public.availability_slots(user_id, event_type_id, kind, start_time, end_time);

-- Effective bookable ranges for one meeting type, clipped to the window.
--
-- `p_include_shared_open` folds in openings that target every meeting type
-- (`event_type_id is null`). The owner's grid turns it off so a shared opening
-- is drawn once as shared rather than repeated under every type; the public
-- booking paths leave it on. Exceptions are never scoped away: a shared
-- exception always applies.
create or replace function public.scheduling_available_ranges(
  p_user_id uuid,
  p_event_type_id uuid,
  p_start_time timestamptz,
  p_end_time timestamptz,
  p_include_shared_open boolean default true
)
returns table(range_start timestamptz, range_end timestamptz)
language sql
stable
security definer
set search_path = public
as $$
  with event_type as (
    select event_type.timezone, event_type.weekly_availability
    from public.scheduling_event_types event_type
    where event_type.id = p_event_type_id
      and event_type.user_id = p_user_id
  ),
  weekly_rules as (
    select event_type.timezone,
      rule."dayOfWeek", rule."startMinute", rule."endMinute"
    from event_type
    cross join lateral jsonb_to_recordset(event_type.weekly_availability)
      as rule("dayOfWeek" integer, "startMinute" integer, "endMinute" integer)
  ),
  -- The window is padded by a day on each side so a rule whose local day falls
  -- just outside the window still contributes its overlapping tail.
  weekly_spans as (
    select tstzrange(
      (day.local_day + make_interval(mins => rule."startMinute"))
        at time zone rule.timezone,
      (day.local_day + make_interval(mins => rule."endMinute"))
        at time zone rule.timezone,
      '[)'
    ) as span
    from weekly_rules rule
    cross join lateral generate_series(
      ((p_start_time at time zone rule.timezone)::date - 1)::timestamp,
      ((p_end_time at time zone rule.timezone)::date + 1)::timestamp,
      interval '1 day'
    ) as day(local_day)
    where extract(dow from day.local_day)::integer = rule."dayOfWeek"
  ),
  open_spans as (
    select span from weekly_spans
    union all
    select tstzrange(slot.start_time, slot.end_time, '[)')
    from public.availability_slots slot
    where slot.user_id = p_user_id
      and slot.kind = 'open'
      and (
        slot.event_type_id = p_event_type_id
        or (p_include_shared_open and slot.event_type_id is null)
      )
  ),
  blocked_spans as (
    select tstzrange(slot.start_time, slot.end_time, '[)') as span
    from public.availability_slots slot
    where slot.user_id = p_user_id
      and slot.kind = 'blocked'
      and (slot.event_type_id = p_event_type_id or slot.event_type_id is null)
  ),
  resolved as (
    select (
      coalesce((select range_agg(span) from open_spans), '{}'::tstzmultirange)
      - coalesce((select range_agg(span) from blocked_spans), '{}'::tstzmultirange)
    ) * tstzmultirange(tstzrange(p_start_time, p_end_time, '[)')) as spans
  )
  select lower(part), upper(part)
  from resolved
  cross join lateral unnest(resolved.spans) as part
  where not isempty(part)
$$;

-- Takes an explicit user id, so it must never be reachable by an end user.
revoke all on function public.scheduling_available_ranges(
  uuid, uuid, timestamptz, timestamptz, boolean
) from public, anon, authenticated;

-- Absorbs a range into the same-kind rows it touches. Adjacent rows are merged
-- too, so repeated painting can't grow the table without bound.
create or replace function public.merge_availability_slot(
  p_user_id uuid,
  p_event_type_id uuid,
  p_kind text,
  p_start_time timestamptz,
  p_end_time timestamptz
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_start timestamptz := p_start_time;
  v_end timestamptz := p_end_time;
begin
  select
    least(p_start_time, coalesce(min(slot.start_time), p_start_time)),
    greatest(p_end_time, coalesce(max(slot.end_time), p_end_time))
  into v_start, v_end
  from public.availability_slots slot
  where slot.user_id = p_user_id
    and slot.event_type_id is not distinct from p_event_type_id
    and slot.kind = p_kind
    and slot.start_time <= p_end_time
    and slot.end_time >= p_start_time;

  delete from public.availability_slots slot
  where slot.user_id = p_user_id
    and slot.event_type_id is not distinct from p_event_type_id
    and slot.kind = p_kind
    and slot.start_time <= p_end_time
    and slot.end_time >= p_start_time;

  insert into public.availability_slots (
    user_id, event_type_id, kind, start_time, end_time
  ) values (
    p_user_id, p_event_type_id, p_kind, v_start, v_end
  );
end;
$$;

revoke all on function public.merge_availability_slot(
  uuid, uuid, text, timestamptz, timestamptz
) from public, anon, authenticated;

-- Cuts a range out of the same-kind rows it overlaps, keeping the surviving
-- head and tail of each row.
create or replace function public.subtract_availability_slot(
  p_user_id uuid,
  p_event_type_id uuid,
  p_kind text,
  p_start_time timestamptz,
  p_end_time timestamptz
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_slot public.availability_slots%rowtype;
begin
  for v_slot in
    select *
    from public.availability_slots slot
    where slot.user_id = p_user_id
      and slot.event_type_id is not distinct from p_event_type_id
      and slot.kind = p_kind
      and slot.start_time < p_end_time
      and slot.end_time > p_start_time
    for update
  loop
    delete from public.availability_slots where id = v_slot.id;

    if v_slot.start_time < p_start_time then
      insert into public.availability_slots (
        user_id, event_type_id, kind, start_time, end_time
      ) values (
        p_user_id, p_event_type_id, p_kind, v_slot.start_time, p_start_time
      );
    end if;

    if v_slot.end_time > p_end_time then
      insert into public.availability_slots (
        user_id, event_type_id, kind, start_time, end_time
      ) values (
        p_user_id, p_event_type_id, p_kind, p_end_time, v_slot.end_time
      );
    end if;
  end loop;
end;
$$;

revoke all on function public.subtract_availability_slot(
  uuid, uuid, text, timestamptz, timestamptz
) from public, anon, authenticated;

-- Painting and unpainting are now symmetric: each writes its own kind and
-- clears the opposite one, so the two layers can never both claim a range.
-- Runs as definer to reach the helpers below; every statement is scoped to
-- auth.uid(), and a supplied meeting type must belong to the caller.
create or replace function public.set_availability_range(
  p_start_time timestamptz,
  p_end_time timestamptz,
  p_open boolean,
  p_event_type_id uuid default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
begin
  if v_user_id is null then
    raise exception 'Unauthorized';
  end if;
  if p_end_time <= p_start_time then
    raise exception 'Availability end must be after start';
  end if;
  if p_event_type_id is not null and not exists (
    select 1 from public.scheduling_event_types
    where id = p_event_type_id and user_id = v_user_id
  ) then
    raise exception 'Meeting type not found';
  end if;

  perform pg_advisory_xact_lock(hashtext(v_user_id::text));

  if p_open then
    perform public.subtract_availability_slot(
      v_user_id, p_event_type_id, 'blocked', p_start_time, p_end_time
    );
    perform public.merge_availability_slot(
      v_user_id, p_event_type_id, 'open', p_start_time, p_end_time
    );
  else
    perform public.subtract_availability_slot(
      v_user_id, p_event_type_id, 'open', p_start_time, p_end_time
    );
    perform public.merge_availability_slot(
      v_user_id, p_event_type_id, 'blocked', p_start_time, p_end_time
    );
  end if;
end;
$$;

revoke all on function public.set_availability_range(
  timestamptz, timestamptz, boolean, uuid
) from public, anon, authenticated;
grant execute on function public.set_availability_range(
  timestamptz, timestamptz, boolean, uuid
) to authenticated;

-- The owner's grid: resolved ranges per meeting type, plus shared openings
-- reported once with a null event type.
create or replace function public.get_scheduling_availability(
  p_start_time timestamptz,
  p_end_time timestamptz
)
returns table(id text, start_time timestamptz, end_time timestamptz, event_type_id uuid)
language sql
stable
security definer
set search_path = public
as $$
  with owned as (
    select event_type.id
    from public.scheduling_event_types event_type
    where event_type.user_id = auth.uid()
  ),
  ranges as (
    select resolved.range_start, resolved.range_end, owned.id as event_type_id
    from owned
    cross join lateral public.scheduling_available_ranges(
      auth.uid(), owned.id, p_start_time, p_end_time, false
    ) resolved
    union all
    select resolved.range_start, resolved.range_end, null::uuid
    from public.scheduling_available_ranges(
      auth.uid(), null, p_start_time, p_end_time, true
    ) resolved
  )
  select
    'range:' || coalesce(ranges.event_type_id::text, 'shared') || ':'
      || extract(epoch from ranges.range_start)::bigint::text,
    ranges.range_start,
    ranges.range_end,
    ranges.event_type_id
  from ranges
  where auth.uid() is not null
  order by 2;
$$;

revoke all on function public.get_scheduling_availability(timestamptz, timestamptz)
  from public, anon, authenticated;
grant execute on function public.get_scheduling_availability(timestamptz, timestamptz)
  to authenticated;

-- Public slots, with exceptions subtracted before candidates are generated.
create or replace function public.get_public_schedule_slots(
  p_slug text,
  p_start_time timestamptz,
  p_end_time timestamptz
)
returns table(start_time timestamptz, end_time timestamptz)
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_event_type public.scheduling_event_types%rowtype;
  v_earliest timestamptz;
  v_latest timestamptz;
  v_step integer;
begin
  if p_end_time <= p_start_time or p_end_time > p_start_time + interval '31 days' then
    raise exception 'Schedule range must be between 1 minute and 31 days';
  end if;

  select * into v_event_type
  from public.scheduling_event_types
  where scheduling_event_types.slug = p_slug
    and scheduling_event_types.active = true;

  if not found then return; end if;

  v_step := v_event_type.slot_increment_minutes;
  v_earliest := greatest(
    p_start_time,
    now() + make_interval(mins => v_event_type.min_notice_minutes)
  );
  v_latest := least(
    p_end_time,
    now() + make_interval(days => v_event_type.booking_window_days)
  );

  if v_latest <= v_earliest then return; end if;

  return query
  with availability_ranges as (
    select resolved.range_start, resolved.range_end
    from public.scheduling_available_ranges(
      v_event_type.user_id, v_event_type.id, v_earliest, v_latest, true
    ) resolved
  ),
  candidates as (
    select generated.candidate_start
    from availability_ranges availability
    cross join lateral generate_series(
      availability.range_start
        + ceil(
            extract(epoch from greatest(availability.range_start, v_earliest)
              - availability.range_start) / (v_step * 60)
          )::double precision * make_interval(mins => v_step),
      least(availability.range_end, v_latest)
        - make_interval(mins => v_event_type.duration_minutes),
      make_interval(mins => v_step)
    ) as generated(candidate_start)
  )
  select distinct
    candidate.candidate_start,
    candidate.candidate_start
      + make_interval(mins => v_event_type.duration_minutes)
  from candidates candidate
  where not exists (
    select 1
    from public.events busy
    left join public.bookings booking on booking.event_id = busy.id
    where busy.user_id = v_event_type.user_id
      and (booking.id is null or booking.status in ('pending', 'confirmed'))
      and busy.start_time
        - make_interval(mins => coalesce(booking.buffer_before_minutes, 0))
        < candidate.candidate_start
          + make_interval(
              mins => v_event_type.duration_minutes
                + v_event_type.buffer_after_minutes
            )
      and busy.end_time
        + make_interval(mins => coalesce(booking.buffer_after_minutes, 0))
        > candidate.candidate_start
          - make_interval(mins => v_event_type.buffer_before_minutes)
  )
  order by candidate.candidate_start
  limit 500;
end;
$$;

revoke all on function public.get_public_schedule_slots(text, timestamptz, timestamptz)
  from public, anon, authenticated;
grant execute on function public.get_public_schedule_slots(text, timestamptz, timestamptz)
  to anon, authenticated;

-- Booking and rescheduling still run their own availability check against the
-- weekly rules, which know nothing about exceptions. This is the enforcement
-- point that closes that gap for every writer, present and future.
create or replace function public.enforce_availability_exceptions()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_start timestamptz := new.start_time;
  v_end timestamptz := new.end_time;
begin
  -- This trigger sorts before populate_booking_from_event, so the canonical
  -- times may not be filled in yet.
  if v_start is null or v_end is null then
    select event.start_time, event.end_time
    into v_start, v_end
    from public.events event
    where event.id = new.event_id;
  end if;

  if v_start is null or v_end is null then
    return new;
  end if;

  if exists (
    select 1
    from public.availability_slots slot
    where slot.user_id = new.user_id
      and slot.kind = 'blocked'
      and (
        slot.event_type_id is null
        or slot.event_type_id = new.event_type_id
      )
      and slot.start_time < v_end
      and slot.end_time > v_start
  ) then
    raise exception using errcode = '23P01',
      message = 'This time is no longer available';
  end if;

  return new;
end;
$$;

create trigger bookings_enforce_availability_exceptions
  before insert on public.bookings
  for each row execute function public.enforce_availability_exceptions();
